include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**/*.freezed.dart
    - lib/**.config.dart
    - lib/firebase_options*.dart
    - test/**

linter:
  rules:
    public_member_api_docs: false #개발중 comment 관련
    prefer_relative_imports: true
    prefer_const_constructors: true
    avoid_print: false # 개발 중 print 허용
    always_use_package_imports: false # 상대 경로 import 허용
