name: bigroot_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dart_code_metrics: ^5.7.6
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/image/
    - assets/lottie/
    - assets/svg/