name: bigroot_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  #dart_code_metrics: ^4.19.2
  go_router: ^15.0.0
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #analyzer: 7.3.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/image/
    - assets/lottie/
    - assets/svg/